/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/api-gateway/wrangler.jsonc --env= --include-runtime=false workers/api-gateway/worker-configuration.d.ts` (hash: 507b14fb52e680312ec33d975dc598d1)
interface __BaseEnv_Env {
	SPEC_ATTACHMENTS: R2Bucket;
	NOXSPOT_ASSETS: R2Bucket;
	DB: D1Database;
	TASK_QUEUE: Queue;
	ASSETS: Fetcher;
	PLATFORM_ADMIN_GITHUB_IDS: "196446605";
	GITHUB_APP_ID?: "3652510";
	GITHUB_APP_CLIENT_ID?: "Iv23liSD7Nx3fmV1OQfr";
	SLACK_APP_ID?: "A0BQAKAPG2Y";
	SLACK_ACCEPT_LEGACY_INSTALLS?: "true";
	NOXSPOT_RESPONSE?: Fetcher /* noxspot-api */;
	NOXTICKET_SERVICE?: Fetcher /* noxticket */;
	NOXCUE_RESPONSE?: Fetcher /* noxcue */;
	NOXCUE_INGEST?: Fetcher /* noxcue */;
	NOXFEED_RESPONSE?: Fetcher /* noxfeed-response */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.generated/index");
	}
	interface StagingEnv {
		SPEC_ATTACHMENTS: R2Bucket;
		NOXSPOT_ASSETS: R2Bucket;
		DB: D1Database;
		TASK_QUEUE: Queue;
		ASSETS: Fetcher;
		PLATFORM_ADMIN_GITHUB_IDS: "196446605";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PLATFORM_ADMIN_GITHUB_IDS" | "GITHUB_APP_ID" | "GITHUB_APP_CLIENT_ID" | "SLACK_APP_ID" | "SLACK_ACCEPT_LEGACY_INSTALLS">> {}
}
